require_relative 'examples/inline_simple_initializer_generation'
require_relative 'examples/inline_initializer_with_modifiers_specified'
require_relative 'examples/inline_initializer_with_default_visibility_specified'
