require_relative 'initializer/block_parameter'
require_relative 'initializer/splat_parameter'
require_relative 'initializer/parameter'
require_relative 'initializer/initialization_macro'
require_relative 'initializer/initializer'
