require_relative 'proofs_init'

load 'initializer/accessor_parameter.rb'
load 'initializer/reader_parameter.rb'
load 'initializer/writer_parameter.rb'
load 'initializer/no_accessors_parameter.rb'
load 'initializer/parameter.rb'
load 'initializer/initializer_macro.rb'
load 'initializer/initializer.rb'
load 'initializer/initializer_class_methods.rb'
load 'initializer/parameter_config.rb'
load 'examples.rb'
